apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:7ecef7a64dbc7d002ab63469f9433a71267ed773f7d6ed7821467540aa0a7145
type: application
version: 2.11.2
